# Generated by Django 5.2.6 on 2025-10-18 06:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity_received',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='productstocks',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], db_column='status', default='Normal', max_length=20),
        ),
        # Removed the AlterModelTable operation since the table already has the correct name
        migrations.CreateModel(
            name='ReceiveOrder',
            fields=[
                ('receive_order_code', models.UUIDField(db_column='receive_order_code', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receive_order_id', models.CharField(db_column='receive_order_id', editable=False, max_length=30, unique=True)),
                ('quantity_received', models.PositiveIntegerField(db_column='quantity_received')),
                ('date_received', models.DateTimeField(db_column='date_received', default=django.utils.timezone.now)),
                ('received_by', models.TextField(db_column='received_by')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='inventory_system.order', to_field='order_id')),
                ('order_item', models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='inventory_system.orderitem', to_field='order_item_id')),
            ],
            options={
                'db_table': 'receive_order',
            },
        ),
    ]
