# Generated by Django 5.2.6 on 2025-10-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.TextField(blank=True, db_column='category_description', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='product_count',
            field=models.PositiveIntegerField(db_column='product_count', default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_threshold_days',
            field=models.PositiveIntegerField(db_column='expiry_threshold_days', default=30),
        ),
        migrations.AddField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_column='last_update'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(db_column='low_stock_threshold', default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='on_hand',
            field=models.PositiveIntegerField(db_column='on_hand', default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.PositiveIntegerField(db_column='reserved', default=0),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='on_hand',
            field=models.PositiveIntegerField(db_column='on_hand', default=0),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='status',
            field=models.CharField(db_column='status', default='ACTIVE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, db_column='address', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.TextField(blank=True, db_column='contact_person', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, db_column='phone_number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='expiry_date',
            field=models.DateField(db_column='expiry_date'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
