# Generated by Django 5.2.6 on 2025-10-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0002_remove_orderitem_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productstocks',
            table='product_stocks',
        ),
    ]
