# Generated by Django 5.2.6 on 2025-10-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0002_remove_product_location_remove_productbatch_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_column='product_name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='expiry_date',
            field=models.DateField(db_column='expiry_date', db_index=True),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Near Expiry', 'Near Expiry'), ('Expired', 'Expired'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], db_column='status', max_length=20),
        ),
    ]
