# Generated by Django 5.2.6 on 2025-10-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0003_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_per_unit',
        ),
    ]
