# Generated by Django 5.2.6 on 2025-10-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0003_alter_productstocks_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supplierproduct',
            table='supplier_product',
        ),
    ]
