# Generated by Django 5.2.7 on 2025-10-21 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0004_alter_supplierproduct_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplying_product',
            field=models.ForeignKey(db_column='product_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory_system.product', to_field='product_id'),
            preserve_default=False,
        ),
    ]
