# Generated by Django 5.2.6 on 2025-10-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='received_by',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Received', 'Partially Received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_column='status', default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Near Expiry', 'Near Expiry'), ('Expired', 'Expired'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], db_column='status', default='Normal', max_length=20),
        ),
    ]
