# Generated by Django 5.2.7 on 2025-10-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0005_supplier_supplying_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_column='status', default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='productstocks',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Near Expiry', 'Near Expiry'), ('Expired', 'Expired'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], db_column='status', default='Normal', max_length=20),
        ),
    ]
