# Generated by Django 5.2.7 on 2025-10-21 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0006_supplier_status_alter_productstocks_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplying_product',
            new_name='product_id',
        ),
    ]
