# Generated by Django 5.2.6 on 2025-10-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0006_remove_order_received_by_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispenseitem',
            name='dispense',
        ),
        migrations.RemoveField(
            model_name='dispenseevent',
            name='dispense',
        ),
        migrations.RemoveField(
            model_name='dispenseitem',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='dispenseitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='orderItem',
            field=models.ForeignKey(db_column='order_item_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory_system.orderitem', to_field='order_item_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.ForeignKey(db_column='supplier_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory_system.supplier', to_field='supplier_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Received', 'Partially Received'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], db_column='status', default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Dispense',
        ),
        migrations.DeleteModel(
            name='DispenseEvent',
        ),
        migrations.DeleteModel(
            name='DispenseItem',
        ),
        migrations.DeleteModel(
            name='OrderEvent',
        ),
    ]
