# Generated by Django 5.2.6 on 2025-10-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0007_remove_dispenseitem_dispense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderItem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_column='order_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory_system.order', to_field='order_id'),
            preserve_default=False,
        ),
    ]
