# Generated by Django 5.2.7 on 2025-10-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0007_rename_supplying_product_supplier_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_column='product_name', max_length=255, null=True),
        ),
    ]
