# Generated by Django 5.2.6 on 2025-10-12 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0008_remove_order_orderitem_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_system.order', to_field='order_id'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_cost',
            field=models.DecimalField(db_column='total_cost', decimal_places=2, default=0, max_digits=12),
        ),
    ]
