# Generated by Django 5.2.7 on 2025-10-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0008_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='product_id',
            new_name='product',
        ),
    ]
