# Generated by Django 5.2.7 on 2025-10-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0009_rename_product_id_supplier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='product_count',
            field=models.PositiveIntegerField(db_column='product_count', default=0),
        ),
    ]
