# Generated by Django 5.2.6 on 2025-10-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0009_alter_orderitem_order_alter_orderitem_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Near Expiry', 'Near Expiry'), ('Expired', 'Expired'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], db_column='status', default='Normal', max_length=20),
        ),
    ]
