# Generated by Django 5.2.6 on 2025-10-16 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0010_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='after',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='before',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='related_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateTimeField(db_column='date_of_transaction', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='on_hand',
            field=models.IntegerField(db_column='on_hand', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(blank=True, db_column='remarks', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ', 'Stock Adjustment')], db_column='transaction_type', max_length=20),
        ),
    ]
