# Generated by Django 5.2.7 on 2025-10-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0011_category_status_subcategory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], db_column='status', default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], db_column='status', default='Active', max_length=20),
        ),
    ]
