# Generated by Django 5.2.6 on 2025-10-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0011_remove_transaction_after_remove_transaction_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_id',
            field=models.CharField(db_column='order_item_id', editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='batch_id',
            field=models.CharField(db_column='batch_id', editable=False, max_length=30, unique=True),
        ),
    ]
