# Generated by Django 5.2.7 on 2025-10-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0012_product_status_supplierproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproduct',
            name='status',
        ),
    ]
