# Generated by Django 5.2.7 on 2025-10-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0014_category_archive_reason_category_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
