# Generated by Django 5.2.7 on 2025-10-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0015_alter_category_archived_at_alter_product_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivelog',
            name='object_id',
            field=models.CharField(max_length=50),
        ),
    ]
