# Generated by Django 5.2.7 on 2025-10-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0016_alter_archivelog_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_column='last_updated'),
        ),
    ]
