# Generated by Django 5.2.7 on 2025-11-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0017_product_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveorder',
            name='expiry_date',
            field=models.DateField(blank=True, db_column='expiry_date', help_text='Actual expiry date from product packaging', null=True),
        ),
    ]
