# Generated by Django 5.2.7 on 2025-11-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0018_receiveorder_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveorder',
            name='remarks',
            field=models.TextField(blank=True, db_column='remarks', help_text='Additional notes or remarks for this receive', null=True),
        ),
    ]
