# Generated by Django 5.2.7 on 2025-11-13 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0019_receiveorder_remarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('user_info_code', models.UUIDField(db_column='user_info_code', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_info_id', models.CharField(db_column='user_info_id', editable=False, max_length=20, unique=True)),
                ('middle_name', models.CharField(blank=True, db_column='middle_name', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, db_column='address', null=True)),
                ('role', models.CharField(choices=[('Admin', 'Administrator'), ('Manager', 'Manager'), ('Staff', 'Staff'), ('Viewer', 'Viewer')], db_column='role', default='Staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_information', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_information',
                'ordering': ['-created_at'],
            },
        ),
    ]
