# Generated by Django 5.2.7 on 2025-11-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0020_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Staff', 'Staff'), ('Clerk', 'Clerk')], db_column='role', default='Staff', max_length=20),
        ),
    ]
