# Generated by Django 5.2.6 on 2025-09-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='batch_id',
            field=models.CharField(db_column='batch_id', editable=False, max_length=20, unique=True),
        ),
    ]
