# Generated by Django 5.2.6 on 2025-09-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_productbatch_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='reserved',
            field=models.PositiveIntegerField(db_column='reserved', default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('REJECTED', 'Rejected'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_column='status', default='PENDING', max_length=10),
        ),
    ]
