# Generated by Django 5.2.6 on 2025-09-22 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_productbatch_reserved_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='batch',
            field=models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='config.productbatch', to_field='batch_id'),
        ),
    ]
