# Generated by Django 5.2.6 on 2025-09-23 11:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_orderitem_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseEvent',
            fields=[
                ('event_code', models.UUIDField(db_column='event_code', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_column='event_id', editable=False, max_length=20, unique=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('APPROVED', 'Approved'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], db_column='event_type', max_length=20)),
                ('previous_status', models.CharField(db_column='previous_status', max_length=10)),
                ('new_status', models.CharField(db_column='new_status', max_length=10)),
                ('performed_by', models.TextField(db_column='performed_by')),
                ('timestamp', models.DateTimeField(db_column='timestamp', default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('dispense', models.ForeignKey(db_column='dispense_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='config.dispense', to_field='dispense_id')),
            ],
            options={
                'db_table': 'dispense_event',
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('event_code', models.UUIDField(db_column='event_code', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_column='event_id', editable=False, max_length=20, unique=True)),
                ('event_type', models.CharField(db_column='event_type', max_length=20)),
                ('previous_status', models.CharField(db_column='previous_status', max_length=10)),
                ('new_status', models.CharField(db_column='new_status', max_length=10)),
                ('performed_by', models.TextField(db_column='performed_by')),
                ('timestamp', models.DateTimeField(db_column='timestamp', default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='config.order', to_field='order_id')),
            ],
            options={
                'db_table': 'order_event',
            },
        ),
    ]
