# Generated by Django 5.2.6 on 2025-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_dispenseevent_orderevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='previous_status',
            field=models.CharField(db_column='previous_status', max_length=10, null=True),
        ),
    ]
