# Generated by Django 5.2.6 on 2025-09-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_alter_orderevent_previous_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(db_column='category_id', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.CharField(db_column='location_id', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_column='order_id', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(db_column='supplier_id', editable=False, max_length=15, unique=True),
        ),
    ]
