# Generated by Django 5.2.6 on 2025-09-23 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_category_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.ForeignKey(db_column='supplier_id', default='SUP-001', on_delete=django.db.models.deletion.CASCADE, to='config.supplier', to_field='supplier_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='supplier_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='config.supplier', to_field='supplier_id'),
        ),
    ]
