# Generated by Django 5.2.6 on 2025-09-23 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_orderitem_supplier_alter_order_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='config.supplier', to_field='supplier_id'),
        ),
    ]
